version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: e-repository-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-e_repository_db}
      MYSQL_USER: ${MYSQL_USER:-erepo_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-erepo_pass}
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  api:
    build: ./backend
    container_name: e-repository-api
    restart: unless-stopped
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-erepo_user}
      - DB_PASSWORD=${DB_PASSWORD:-erepo_pass}
      - DB_NAME=${DB_NAME:-e_repository_db}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-24h}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy
      pdf-service:
        condition: service_started

  pdf-service:
    build: ./pdf-service
    container_name: e-repository-pdf-service
    restart: unless-stopped
    ports:
      - "${PDF_SERVICE_PORT:-8000}:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: e-repository-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080}
    depends_on:
      - api

volumes:
  mysql_data:
